version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:

  build-and-test:
    executor:
      name: python/default
      tag: '3.9'
    # working_directory: ~/project/Backend
    steps:
      - checkout:
          path: ~/project/Backend
      - run: ls -a

      # - save_cache:
      #     paths:
      #       - ./venv
      #     key: v1-dependencies-{{ checksum "./Backend/requirements.txt" }}
      # - restore_cache:
      #       keys:
      #         - v1-dependencies-{{ checksum "./Backend/requirements.txt" }}
      #         # fallback to using the latest cache if no exact match is found
      #         - v1-dependencies-
      # - checkout

      - run:
          name: Create requirements.txt
          command: pip freeze requirements.txt
      
      # - run:
      #     name: Go back to backend
      #     command: cd Backend

      - run:
          name: Install dependencies
          command: pip3 install -r requirements.txt
      

      - run: 
          name: Database setup
          command: python3.9 database.py
      - run:
          name: Run the API
          command: uvicorn main:app --reload  
      

workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - "circleci-testing"