version: 2.1

orbs:
  python: circleci/python@2.1.1
  jira: circleci/jira@1.3.1
  aws-cli: circleci/aws-cli@1.2.1

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: '3.9'
    working_directory: ~/project/Backend
    steps:
      - checkout:
          path: ~/project/Backend

      # - save_cache:
      #     paths:
      #       - ./venv
      #     key: v1-dependencies-{{ checksum "./Backend/requirements.txt" }}
      # - restore_cache:
      #       keys:
      #         - v1-dependencies-{{ checksum "./Backend/requirements.txt" }}
      #         # fallback to using the latest cache if no exact match is found
      #         - v1-dependencies-
      # - checkout

      - run:
          name: Find requirements.txt
          command: find . -regex '.*requirements.txt$'

      - run: 
          name: Checking of backend folders
          command: ls ./Backend -a
      - run:
          name: Install dependencies
          command: pip3 install -r ./Backend/requirements.txt

      # - run: cd ./Backend/
    
      # - run:
      #     name: Go back to backend
      #     command: cd Backend

      - run:
          name: Database Setup
          command: echo $DATABASE_URL

      # - run: 
      #     name: Database setup
      #     command: python3.9 ./Backend/database.py

      - run:
          name: Run Test File
          # command: uvicorn Backend.main:app --reload
          command: pytest ./Backend/testrun.py

      # - run:
      #     name: Run the API
      #     command: uvicorn Backend.main:app --reload  

      # - run:
      #     name: Show Python folder
      #     command: pip --version

      # - run:
      #     name: Create Zipfile archive of Dependencies
      #     command: |
      #       cd /home/circleci/.pyenv/versions/3.9.13/lib/python3.9/site-packages
      #       zip -r9 ../../../../../../../../function.zip .
            
     
      - run:
          name: Add backend to Zipfile
          command: zip -g ./function.zip -r ./Backend/

      - run: 
          name: Check root folder
          command: ls /home/circleci/project/Backend -a

      - persist_to_workspace:
          root: .
          paths:
            - function.zip


  deploy-dev:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ./
      - aws-cli/setup:
          aws-region: AWS_DEFAULT_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: Upload to S3 
          command: aws s3 cp function.zip s3://spm-bigbucket/function.zip
      - run:        
          name: Deploy new Lambda        
          command: aws lambda update-function-code --function-name spm_fastapi --s3-bucket spm-bigbucket --s3-key function.zip
      

workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - "circleci-deployment"
          context:
            - Database
            - Deployment
      - deploy-dev:
          context:
            - Deployment
          requires:
            - build-and-test    
          filters:        
            branches:
              only:
                - "circleci-deployment"


